version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meliscraper-api
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      PORT: "${PORT:-8080}"
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-meliscraper}"
      POSTGRES_HOST: postgresql
    networks:
      - meliscraper-api-network

  postgresql:
    container_name: meliscraper-database
    image: postgres:18-alpine
    networks:
      - meliscraper-api-network
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-meliscraper}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  postgres_data:
    driver: local

networks:
  meliscraper-api-network:
    name: meliscraper-api-network
    driver: bridge
